namespace Ryo.Definitions.Enums;

public enum CriAtomExPlayerStatusTag
{
    CRIATOMEXPLAYER_STATUS_STOP,
    CRIATOMEXPLAYER_STATUS_PREP,
    CRIATOMEXPLAYER_STATUS_PLAYING,
    CRIATOMEXPLAYER_STATUS_PLAYEND,
    CRIATOMEXPLAYER_STATUS_ERROR,
}
